version: '3'

services:
  app:
    container_name: arifandi-id
    restart: always
    build: .
    ports: 
      - '80:5000'
    volumes:
      - ./public/:/usr/src/app/public/
      - ./src/:/usr/src/app/src/